'use strict';

export type BcostModuleArea =
  | 'SaaS'
  | 'Fiscal'
  | 'Banking'
  | 'Financeiro'
  | 'Contábil'
  | 'Folha'
  | 'Compliance'
  | 'Automação'
  | 'Integrações'
  | 'Segurança';

export type BcostModuleStatus = 'ACTIVE' | 'INTEGRATING' | 'PLANNED';

export type BcostModulePriority = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';

export type BcostSchemaModule = {
  slug: string;
  title: string;
  model: string;
  area: BcostModuleArea;
  status: BcostModuleStatus;
  priority: BcostModulePriority;
  description: string;
  commercialValue: string;
  route: string;
  apiBase?: string;
  mainActions: string[];
  kpis: string[];
};

export const bcostSchemaModules: BcostSchemaModule[] = [
  {
    slug: 'users',
    title: 'Usuários',
    model: 'User',
    area: 'SaaS',
    status: 'INTEGRATING',
    priority: 'CRITICAL',
    description: 'Gestão de usuários, identidade, status ativo e 2FA.',
    commercialValue: 'Permite operação multiusuário profissional por empresa.',
    route: '/dashboard/modules/users',
    apiBase: '/users',
    mainActions: ['Listar usuários', 'Criar usuário', 'Ativar/desativar', 'Gerenciar 2FA'],
    kpis: ['Usuários ativos', 'Usuários inativos', '2FA ativo'],
  },
  {
    slug: 'sessions',
    title: 'Sessões',
    model: 'UserSession',
    area: 'Segurança',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Sessões autenticadas, dispositivos, IPs e expiração.',
    commercialValue: 'Aumenta segurança e confiança enterprise.',
    route: '/dashboard/modules/sessions',
    apiBase: '/auth/sessions',
    mainActions: ['Ver sessões', 'Revogar sessão', 'Auditar IP', 'Forçar logout'],
    kpis: ['Sessões ativas', 'Sessões expiradas', 'Dispositivos únicos'],
  },
  {
    slug: 'companies',
    title: 'Empresas',
    model: 'Company',
    area: 'SaaS',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Cadastro multi-tenant de empresas, CNPJ, regime tributário e plano.',
    commercialValue: 'Base SaaS para operar múltiplas empresas e planos.',
    route: '/dashboard/companies',
    apiBase: '/company',
    mainActions: ['Criar empresa', 'Editar empresa', 'Selecionar tenant', 'Gerenciar plano'],
    kpis: ['Empresas ativas', 'Plano atual', 'Regime tributário'],
  },
  {
    slug: 'company-users',
    title: 'Usuários por Empresa',
    model: 'CompanyUser',
    area: 'SaaS',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'RBAC por empresa: OWNER, ACCOUNTANT, MANAGER e VIEWER.',
    commercialValue: 'Essencial para escritórios contábeis e times internos.',
    route: '/dashboard/modules/company-users',
    apiBase: '/company-users',
    mainActions: ['Convidar usuário', 'Alterar papel', 'Remover acesso', 'Auditar permissões'],
    kpis: ['Owners', 'Accountants', 'Managers', 'Viewers'],
  },
  {
    slug: 'invoices',
    title: 'Notas Fiscais',
    model: 'Invoice',
    area: 'Fiscal',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'NF-e, NFS-e, notas de serviço/produto/compra, XML e status fiscal.',
    commercialValue: 'Núcleo fiscal do produto e fonte de inteligência tributária.',
    route: '/dashboard/invoices',
    apiBase: '/fiscal/invoices',
    mainActions: ['Listar notas', 'Enviar XML', 'Registrar nota', 'Cancelar/substituir'],
    kpis: ['Notas emitidas', 'Notas pendentes', 'Notas canceladas', 'Valor total'],
  },
  {
    slug: 'sefaz-events',
    title: 'Eventos SEFAZ',
    model: 'InvoiceSefazEvent',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Eventos fiscais: autorização, cancelamento, contingência e carta de correção.',
    commercialValue: 'Dá rastreabilidade fiscal profissional ao cliente.',
    route: '/dashboard/modules/sefaz-events',
    apiBase: '/fiscal/sefaz-events',
    mainActions: ['Ver timeline', 'Consultar protocolo', 'Auditar evento', 'Exportar histórico'],
    kpis: ['Autorizadas', 'Canceladas', 'Contingências', 'Eventos por mês'],
  },
  {
    slug: 'bank-accounts',
    title: 'Contas Bancárias',
    model: 'BankAccount',
    area: 'Banking',
    status: 'INTEGRATING',
    priority: 'CRITICAL',
    description: 'Contas bancárias, banco, agência, conta e saldo cache.',
    commercialValue: 'Base para conciliação, fluxo de caixa e Open Finance.',
    route: '/dashboard/modules/bank-accounts',
    apiBase: '/banking/accounts',
    mainActions: ['Listar contas', 'Cadastrar conta', 'Conectar Open Finance', 'Importar OFX'],
    kpis: ['Contas conectadas', 'Saldo total', 'Última sincronização'],
  },
  {
    slug: 'bank-transactions',
    title: 'Transações Bancárias',
    model: 'BankTransaction',
    area: 'Banking',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Entradas, saídas, conciliação com notas e obrigações tributárias.',
    commercialValue: 'Diferencial forte contra ERPs antigos: conciliação inteligente.',
    route: '/dashboard/banking',
    apiBase: '/banking/transactions',
    mainActions: ['Listar transações', 'Conciliar', 'Desfazer conciliação', 'Importar extrato'],
    kpis: ['Transações', 'Conciliadas', 'Pendentes', 'Saldo'],
  },

  {
    slug: 'finance-operations',
    title: 'Finance Operations',
    model: 'FinanceOperationsEnterprise',
    description:
      'Cockpit financeiro enterprise com contas a receber, contas a pagar, caixa, aging financeiro, timeline operacional e risco de cashflow.',
    area: 'Banking',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    commercialValue:
      'Aproxima o bCost da camada operacional financeira da Conta Azul, com visão enterprise, multi-tenant, auditável e integrada ao fiscal/bancário.',
    route: '/dashboard/modules/finance-operations',
    apiBase: '/finance/operations',
    mainActions: [
      'Analisar caixa',
      'Ver recebíveis',
      'Ver pagáveis',
      'Controlar vencidos',
      'Projetar cashflow',
    ],
    kpis: ['Finance Score', 'A Receber', 'A Pagar', 'Vencidos', 'Saldo Projetado'],
  },
  {
    slug: 'balance-locks',
    title: 'Travas de Competência',
    model: 'BalanceLock',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Bloqueio de competência mensal após fechamento financeiro/fiscal.',
    commercialValue: 'Evita alterações indevidas e dá governança contábil.',
    route: '/dashboard/modules/balance-locks',
    apiBase: '/finance/balance-locks',
    mainActions: ['Travar mês', 'Destravar com permissão', 'Auditar trava', 'Ver competências'],
    kpis: ['Meses travados', 'Último fechamento', 'Alterações bloqueadas'],
  },
  {
    slug: 'customers',
    title: 'Clientes',
    model: 'Customer',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Clientes, documentos, e-mails e vínculo com notas/contratos.',
    commercialValue: 'Permite CRM financeiro/fiscal integrado.',
    route: '/dashboard/modules/customers',
    apiBase: '/customers',
    mainActions: ['Cadastrar cliente', 'Editar cliente', 'Ver notas', 'Ver contratos'],
    kpis: ['Clientes ativos', 'Clientes inativos', 'Receita por cliente'],
  },
  {
    slug: 'contracts',
    title: 'Contratos',
    model: 'Contract',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Contratos recorrentes, faturamento automático e status comercial.',
    commercialValue: 'Permite receita recorrente e automação de billing operacional.',
    route: '/dashboard/modules/contracts',
    apiBase: '/contracts',
    mainActions: ['Criar contrato', 'Suspender', 'Finalizar', 'Gerar faturamento'],
    kpis: ['Contratos ativos', 'MRR estimado', 'Contratos suspensos'],
  },
  {
    slug: 'tax-obligations',
    title: 'Obrigações Tributárias',
    model: 'TaxObligation',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'DAS, DARF, GPS e obrigações a pagar com vencimento e status.',
    commercialValue: 'Reduz risco fiscal e aumenta retenção do cliente.',
    route: '/dashboard/modules/tax-obligations',
    apiBase: '/tax-obligations',
    mainActions: ['Listar obrigações', 'Marcar como paga', 'Anexar guia', 'Ver vencidas'],
    kpis: ['Pendentes', 'Pagas', 'Vencidas', 'Valor total'],
  },
  {
    slug: 'tax-calculations',
    title: 'Cálculos Tributários',
    model: 'TaxCalculation',
    area: 'Fiscal',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Histórico de cálculos, RBT12, Fator R e memória de cálculo.',
    commercialValue: 'Cria confiança e diferenciação com transparência tributária.',
    route: '/dashboard/intelligence',
    apiBase: '/fiscal/tax',
    mainActions: ['Calcular imposto', 'Ver memória', 'Fechar mês', 'Comparar cenários'],
    kpis: ['Imposto estimado', 'Fator R', 'RBT12', 'Economia'],
  },
  {
    slug: 'fiscal-obligations',
    title: 'Obrigações Fiscais',
    model: 'FiscalObligation',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'SPED, ECD, ECF, DCTF, DEFIS, PGDAS e recibos.',
    commercialValue: 'Aproxima o bCost de soluções como Domínio, Alterdata e SCI.',
    route: '/dashboard/modules/fiscal-obligations',
    apiBase: '/fiscal-obligations',
    mainActions: ['Gerar obrigação', 'Enviar arquivo', 'Anexar recibo', 'Acompanhar status'],
    kpis: ['Pendentes', 'Aceitas', 'Rejeitadas', 'Vencidas'],
  },
  {
    slug: 'employees',
    title: 'Funcionários',
    model: 'Employee',
    area: 'Folha',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Funcionários, CPF, PIS, admissão, regime e salário base.',
    commercialValue: 'Base para folha, Fator R e compliance trabalhista.',
    route: '/dashboard/modules/employees',
    apiBase: '/payroll/employees',
    mainActions: ['Cadastrar funcionário', 'Desligar', 'Editar salário', 'Ver histórico'],
    kpis: ['Ativos', 'Desligados', 'CLT', 'PJ'],
  },
  {
    slug: 'payrolls',
    title: 'Folha Mensal',
    model: 'Payroll',
    area: 'Folha',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Folha, pró-labore, salários e total mensal para Fator R.',
    commercialValue: 'Um dos maiores diferenciais fiscais para Simples Nacional.',
    route: '/dashboard/payroll',
    apiBase: '/fiscal/payroll',
    mainActions: ['Registrar folha', 'Simular pró-labore', 'Fechar competência', 'Ver Fator R'],
    kpis: ['Folha total', 'Pró-labore', 'Fator R', 'Economia possível'],
  },
  {
    slug: 'payroll-entries',
    title: 'Lançamentos de Folha',
    model: 'PayrollEntry',
    area: 'Folha',
    status: 'PLANNED',
    priority: 'MEDIUM',
    description: 'INSS, IRRF, FGTS, benefícios, descontos e salário líquido.',
    commercialValue: 'Permite evoluir para BPO/folha integrada.',
    route: '/dashboard/modules/payroll-entries',
    apiBase: '/payroll/entries',
    mainActions: ['Listar lançamentos', 'Gerar holerite', 'Calcular encargos', 'Exportar folha'],
    kpis: ['INSS', 'IRRF', 'FGTS', 'Salário líquido'],
  },
  {
    slug: 'account-plan',
    title: 'Plano de Contas',
    model: 'AccountPlan',
    area: 'Contábil',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Plano de contas por empresa e tipo contábil.',
    commercialValue: 'Necessário para competir com ERPs contábeis tradicionais.',
    route: '/dashboard/modules/account-plan',
    apiBase: '/accounting/account-plan',
    mainActions: ['Criar conta', 'Editar conta', 'Inativar', 'Importar plano'],
    kpis: ['Ativo', 'Passivo', 'Receita', 'Despesa'],
  },
  {
    slug: 'accounting-entries',
    title: 'Lançamentos Contábeis',
    model: 'AccountingEntry',
    area: 'Contábil',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Débito/crédito, origem automática/manual e competência.',
    commercialValue: 'Núcleo contábil para competir com Domínio, SCI e Alterdata.',
    route: '/dashboard/modules/accounting-entries',
    apiBase: '/accounting/entries',
    mainActions: ['Criar lançamento', 'Gerar automático', 'Exportar', 'Bloquear competência'],
    kpis: ['Lançamentos', 'Automáticos', 'Manuais', 'Competências travadas'],
  },
  {
    slug: 'financial-events',
    title: 'Eventos Financeiros',
    model: 'FinancialEvent',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Eventos financeiros: nota emitida, pagamento, imposto, folha e banco.',
    commercialValue: 'Cria linha do tempo financeira auditável.',
    route: '/dashboard/modules/financial-events',
    apiBase: '/finance/events',
    mainActions: ['Ver eventos', 'Filtrar por origem', 'Exportar', 'Auditar'],
    kpis: ['Recebimentos', 'Pagamentos', 'Impostos', 'Eventos manuais'],
  },
  {
    slug: 'financial-snapshots',
    title: 'Snapshots Financeiros',
    model: 'FinancialSnapshot',
    area: 'Financeiro',
    status: 'INTEGRATING',
    priority: 'CRITICAL',
    description: 'DRE mensal, imposto, lucro líquido e hash de integridade.',
    commercialValue: 'Permite fechamento mensal confiável e auditável.',
    route: '/dashboard/modules/financial-snapshots',
    apiBase: '/finance/snapshots',
    mainActions: ['Gerar snapshot', 'Ver DRE', 'Validar hash', 'Comparar meses'],
    kpis: ['Receita', 'Despesas', 'Imposto', 'Lucro líquido'],
  },
  {
    slug: 'cash-flow-projections',
    title: 'Projeção de Caixa',
    model: 'CashFlowProjection',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Previsões de caixa e alertas preditivos.',
    commercialValue: 'Funcionalidade de alto valor percebido para PMEs.',
    route: '/dashboard/modules/cash-flow-projections',
    apiBase: '/finance/cash-flow',
    mainActions: ['Gerar projeção', 'Ver risco', 'Simular cenário', 'Criar alerta'],
    kpis: ['Saldo projetado', 'Risco de caixa', 'Dias até insuficiência'],
  },
  {
    slug: 'audit-logs',
    title: 'Auditoria',
    model: 'AuditLog',
    area: 'Segurança',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Trilha de auditoria por usuário, empresa, entidade e ação.',
    commercialValue: 'Obrigatório para LGPD, enterprise e confiança contábil.',
    route: '/dashboard/modules/audit-logs',
    apiBase: '/audit',
    mainActions: ['Ver logs', 'Filtrar ação', 'Exportar auditoria', 'Investigar evento'],
    kpis: ['Eventos', 'Erros', 'Usuários ativos', 'Tempo médio'],
  },
  {
    slug: 'notifications',
    title: 'Notificações',
    model: 'NotificationLog',
    area: 'SaaS',
    status: 'INTEGRATING',
    priority: 'HIGH',
    description: 'Central de notificações, leitura, reconhecimento e severidade.',
    commercialValue: 'Aumenta engajamento e reduz risco de obrigações esquecidas.',
    route: '/dashboard/modules/notifications',
    apiBase: '/notifications',
    mainActions: ['Listar notificações', 'Marcar como lida', 'Reconhecer', 'Filtrar severidade'],
    kpis: ['Pendentes', 'Críticas', 'Lidas', 'Arquivadas'],
  },
  {
    slug: 'compliance-checks',
    title: 'Compliance Fiscal',
    model: 'ComplianceCheck',
    area: 'Compliance',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Pendências fiscais, severidade, status e resolução.',
    commercialValue: 'Diferencial direto contra contabilidades reativas.',
    route: '/dashboard/compliance',
    apiBase: '/fiscal/compliance',
    mainActions: ['Executar auditoria', 'Resolver pendência', 'Ignorar', 'Gerar relatório'],
    kpis: ['Abertas', 'Resolvidas', 'Críticas', 'Em progresso'],
  },
  {
    slug: 'automation-jobs',
    title: 'Automações',
    model: 'AutomationJob',
    area: 'Automação',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Jobs de automação, progresso, payload, resultado e erro.',
    commercialValue: 'Transforma o bCost em operação automatizada, não só sistema.',
    route: '/dashboard/modules/automation-jobs',
    apiBase: '/automation/jobs',
    mainActions: ['Ver jobs', 'Reprocessar', 'Cancelar', 'Auditar falha'],
    kpis: ['Na fila', 'Executando', 'Concluídos', 'Falhos'],
  },

  {
    slug: 'command-center',
    title: 'Command Center',
    model: 'CommandCenterEnterprise',
    description:
      'Executive Operations Center com score, riscos, módulos, auditoria e atividade operacional consolidada.',
    area: 'Automação',
    status: 'PLANNED',
    priority: 'HIGH',
    commercialValue:
      'Consolida riscos, operações, auditoria e saúde dos módulos enterprise em uma visão executiva única.',
    route: '/dashboard/modules/command-center',
    apiBase: '/operations/command-center',
    mainActions: ['Ver score executivo', 'Analisar riscos', 'Abrir módulos', 'Auditar atividade'],
    kpis: ['Executive Score', 'Healthy', 'Attention', 'Critical', 'Unread'],
  },

  {
    slug: 'audit-intelligence',
    title: 'Audit Intelligence',
    model: 'AuditIntelligenceEnterprise',
    description:
      'Camada enterprise de inteligência de auditoria com quality score, ruído histórico, sinais ativos, recomendações e observabilidade executiva.',
    area: 'Automação',
    status: 'PLANNED',
    priority: 'HIGH',
    commercialValue:
      'Transforma AuditLog e sinais operacionais em inteligência executiva para governança, suporte e observabilidade premium.',
    route: '/dashboard/modules/audit-intelligence',
    apiBase: '/audit/intelligence',
    mainActions: [
      'Analisar qualidade',
      'Ver sinais ativos',
      'Classificar ruído histórico',
      'Priorizar recomendações',
    ],
    kpis: ['Quality Score', 'Active Signals', 'Historical Noise', 'Server Errors', 'Client Errors'],
  },
  {
    slug: 'business-rules',
    title: 'Regras de Negócio',
    model: 'BusinessRule',
    area: 'Automação',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Regras condicionais com ações automáticas por empresa.',
    commercialValue: 'Permite automação fiscal/financeira sem código para o cliente.',
    route: '/dashboard/modules/business-rules',
    apiBase: '/business-rules',
    mainActions: ['Criar regra', 'Ativar/desativar', 'Testar regra', 'Ver disparos'],
    kpis: ['Ativas', 'Inativas', 'Disparos', 'Última execução'],
  },
  {
    slug: 'digital-certificates',
    title: 'Certificados Digitais',
    model: 'DigitalCertificate',
    area: 'Integrações',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Certificados A1, validade, vencimento e status.',
    commercialValue: 'Obrigatório para automação fiscal real com Receita/SEFAZ.',
    route: '/dashboard/modules/digital-certificates',
    apiBase: '/digital-certificates',
    mainActions: ['Enviar certificado', 'Ver validade', 'Revogar', 'Alertar vencimento'],
    kpis: ['Ativos', 'Expirados', 'A vencer', 'Revogados'],
  },
  {
    slug: 'webhooks',
    title: 'Webhooks',
    model: 'WebhookConfig',
    area: 'Integrações',
    status: 'PLANNED',
    priority: 'MEDIUM',
    description: 'Webhooks por empresa, eventos, segredo e status ativo.',
    commercialValue: 'Essencial para ecossistema SaaS e integrações B2B.',
    route: '/dashboard/modules/webhooks',
    apiBase: '/webhooks',
    mainActions: ['Criar webhook', 'Testar envio', 'Rotacionar segredo', 'Desativar'],
    kpis: ['Ativos', 'Falhas', 'Eventos enviados', 'Último disparo'],
  },
];

export function getSchemaModuleBySlug(slug: string) {
  return bcostSchemaModules.find((module) => module.slug === slug);
}

export function getModulesByArea(area: BcostModuleArea) {
  return bcostSchemaModules.filter((module) => module.area === area);
}

export const bcostModuleAreas: BcostModuleArea[] = [
  'SaaS',
  'Fiscal',
  'Banking',
  'Financeiro',
  'Contábil',
  'Folha',
  'Compliance',
  'Automação',
  'Integrações',
  'Segurança',
];

export function getModuleStats() {
  return {
    total: bcostSchemaModules.length,
    active: bcostSchemaModules.filter((module) => module.status === 'ACTIVE').length,
    integrating: bcostSchemaModules.filter((module) => module.status === 'INTEGRATING').length,
    planned: bcostSchemaModules.filter((module) => module.status === 'PLANNED').length,
    critical: bcostSchemaModules.filter((module) => module.priority === 'CRITICAL').length,
  };
}
