'use strict';

export type BcostModuleArea =
  | 'SaaS'
  | 'Fiscal'
  | 'Banking'
  | 'Financeiro'
  | 'Contábil'
  | 'Folha'
  | 'Patrimônio'
  | 'Societário'
  | 'Escritório'
  | 'Compliance'
  | 'Automação'
  | 'Integrações'
  | 'Consultoria'
  | 'Segurança';

export type BcostModuleStatus = 'ACTIVE' | 'INTEGRATING' | 'PLANNED';

export type BcostModulePriority = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';

export type BcostSchemaModule = {
  slug: string;
  title: string;
  model: string;
  area: BcostModuleArea;
  status: BcostModuleStatus;
  priority: BcostModulePriority;
  description: string;
  commercialValue: string;
  route: string;
  apiBase?: string;
  mainActions: string[];
  kpis: string[];
};

export const bcostSchemaModules: BcostSchemaModule[] = [
  {
    slug: 'users',
    title: 'Usuários',
    model: 'User',
    area: 'SaaS',
    status: 'INTEGRATING',
    priority: 'CRITICAL',
    description: 'Gestão de usuários, identidade, status ativo e 2FA.',
    commercialValue: 'Permite operação multiusuário profissional por empresa.',
    route: '/dashboard/modules/users',
    apiBase: '/users',
    mainActions: ['Listar usuários', 'Criar usuário', 'Ativar/desativar', 'Gerenciar 2FA'],
    kpis: ['Usuários ativos', 'Usuários inativos', '2FA ativo'],
  },
  {
    slug: 'sessions',
    title: 'Sessões',
    model: 'UserSession',
    area: 'Segurança',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Sessões autenticadas, dispositivos, IPs e expiração.',
    commercialValue: 'Aumenta segurança e confiança enterprise.',
    route: '/dashboard/modules/sessions',
    apiBase: '/auth/sessions',
    mainActions: ['Ver sessões', 'Revogar sessão', 'Auditar IP', 'Forçar logout'],
    kpis: ['Sessões ativas', 'Sessões expiradas', 'Dispositivos únicos'],
  },
  {
    slug: 'companies',
    title: 'Empresas',
    model: 'Company',
    area: 'SaaS',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Cadastro multi-tenant de empresas, CNPJ, regime tributário e plano.',
    commercialValue: 'Base SaaS para operar múltiplas empresas e planos.',
    route: '/dashboard/companies',
    apiBase: '/company',
    mainActions: ['Criar empresa', 'Editar empresa', 'Selecionar tenant', 'Gerenciar plano'],
    kpis: ['Empresas ativas', 'Plano atual', 'Regime tributário'],
  },
  {
    slug: 'company-users',
    title: 'Usuários por Empresa',
    model: 'CompanyUser',
    area: 'SaaS',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'RBAC por empresa: OWNER, ACCOUNTANT, MANAGER e VIEWER.',
    commercialValue: 'Essencial para escritórios contábeis e times internos.',
    route: '/dashboard/modules/company-users',
    apiBase: '/company-users',
    mainActions: ['Convidar usuário', 'Alterar papel', 'Remover acesso', 'Auditar permissões'],
    kpis: ['Owners', 'Accountants', 'Managers', 'Viewers'],
  },
  {
    slug: 'invoices',
    title: 'Notas Fiscais',
    model: 'Invoice',
    area: 'Fiscal',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'NF-e, NFS-e, notas de serviço/produto/compra, XML e status fiscal.',
    commercialValue: 'Núcleo fiscal do produto e fonte de inteligência tributária.',
    route: '/dashboard/invoices',
    apiBase: '/fiscal/invoices',
    mainActions: ['Listar notas', 'Enviar XML', 'Registrar nota', 'Cancelar/substituir'],
    kpis: ['Notas emitidas', 'Notas pendentes', 'Notas canceladas', 'Valor total'],
  },
  {
    slug: 'sefaz-events',
    title: 'Eventos SEFAZ',
    model: 'InvoiceSefazEvent',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Eventos fiscais: autorização, cancelamento, contingência e carta de correção.',
    commercialValue: 'Dá rastreabilidade fiscal profissional ao cliente.',
    route: '/dashboard/modules/sefaz-events',
    apiBase: '/fiscal/sefaz-events',
    mainActions: ['Ver timeline', 'Consultar protocolo', 'Auditar evento', 'Exportar histórico'],
    kpis: ['Autorizadas', 'Canceladas', 'Contingências', 'Eventos por mês'],
  },
  {
    slug: 'bank-accounts',
    title: 'Contas Bancárias',
    model: 'BankAccount',
    area: 'Banking',
    status: 'INTEGRATING',
    priority: 'CRITICAL',
    description: 'Contas bancárias, banco, agência, conta e saldo cache.',
    commercialValue: 'Base para conciliação, fluxo de caixa e Open Finance.',
    route: '/dashboard/modules/bank-accounts',
    apiBase: '/banking/enterprise/accounts',
    mainActions: ['Listar contas', 'Cadastrar conta', 'Conectar Open Finance', 'Importar OFX'],
    kpis: ['Contas conectadas', 'Saldo total', 'Última sincronização'],
  },
  {
    slug: 'bank-transactions',
    title: 'Transações Bancárias',
    model: 'BankTransaction',
    area: 'Banking',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Entradas, saídas, conciliação com notas e obrigações tributárias.',
    commercialValue: 'Diferencial forte contra ERPs antigos: conciliação inteligente.',
    route: '/dashboard/modules/bank-transactions',
    apiBase: '/banking/enterprise/transactions',
    mainActions: ['Listar transações', 'Conciliar', 'Desfazer conciliação', 'Importar extrato'],
    kpis: ['Transações', 'Conciliadas', 'Pendentes', 'Saldo'],
  },

  {
    slug: 'finance-operations',
    title: 'Finance Operations',
    model: 'FinanceOperationsEnterprise',
    description:
      'Cockpit financeiro enterprise com contas a receber, contas a pagar, caixa, aging financeiro, timeline operacional e risco de cashflow.',
    area: 'Banking',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    commercialValue:
      'Aproxima o bCost da camada operacional financeira esperada por PMEs, com visão enterprise, multi-tenant, auditável e integrada ao fiscal/bancário.',
    route: '/dashboard/modules/finance-operations',
    apiBase: '/finance/operations',
    mainActions: [
      'Analisar caixa',
      'Ver recebíveis',
      'Ver pagáveis',
      'Controlar vencidos',
      'Projetar cashflow',
    ],
    kpis: ['Finance Score', 'A Receber', 'A Pagar', 'Vencidos', 'Saldo Projetado'],
  },
  {
    slug: 'balance-locks',
    title: 'Travas de Competência',
    model: 'BalanceLock',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Bloqueio de competência mensal após fechamento financeiro/fiscal.',
    commercialValue: 'Evita alterações indevidas e dá governança contábil.',
    route: '/dashboard/modules/balance-locks',
    apiBase: '/finance/balance-locks',
    mainActions: ['Travar mês', 'Destravar com permissão', 'Auditar trava', 'Ver competências'],
    kpis: ['Meses travados', 'Último fechamento', 'Alterações bloqueadas'],
  },
  {
    slug: 'customers',
    title: 'Clientes',
    model: 'Customer',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Clientes, documentos, e-mails e vínculo com notas/contratos.',
    commercialValue: 'Permite CRM financeiro/fiscal integrado.',
    route: '/dashboard/modules/customers',
    apiBase: '/customers',
    mainActions: ['Cadastrar cliente', 'Editar cliente', 'Ver notas', 'Ver contratos'],
    kpis: ['Clientes ativos', 'Clientes inativos', 'Receita por cliente'],
  },
  {
    slug: 'contracts',
    title: 'Contratos',
    model: 'Contract',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Contratos recorrentes, faturamento automático e status comercial.',
    commercialValue: 'Permite receita recorrente e automação de billing operacional.',
    route: '/dashboard/modules/contracts',
    apiBase: '/contracts',
    mainActions: ['Criar contrato', 'Suspender', 'Finalizar', 'Gerar faturamento'],
    kpis: ['Contratos ativos', 'MRR estimado', 'Contratos suspensos'],
  },
  {
    slug: 'tax-obligations',
    title: 'Obrigações Tributárias',
    model: 'TaxObligation',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'DAS, DARF, GPS e obrigações a pagar com vencimento e status.',
    commercialValue: 'Reduz risco fiscal e aumenta retenção do cliente.',
    route: '/dashboard/modules/tax-obligations',
    apiBase: '/tax-obligations',
    mainActions: ['Listar obrigações', 'Marcar como paga', 'Anexar guia', 'Ver vencidas'],
    kpis: ['Pendentes', 'Pagas', 'Vencidas', 'Valor total'],
  },
  {
    slug: 'tax-calculations',
    title: 'Cálculos Tributários',
    model: 'TaxCalculation',
    area: 'Fiscal',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Histórico de cálculos, RBT12, Fator R e memória de cálculo.',
    commercialValue: 'Cria confiança e diferenciação com transparência tributária.',
    route: '/dashboard/intelligence',
    apiBase: '/fiscal/tax',
    mainActions: ['Calcular imposto', 'Ver memória', 'Fechar mês', 'Comparar cenários'],
    kpis: ['Imposto estimado', 'Fator R', 'RBT12', 'Economia'],
  },
  {
    slug: 'fiscal-obligations',
    title: 'Obrigações Fiscais',
    model: 'FiscalObligation',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'SPED, ECD, ECF, DCTF, DEFIS, PGDAS e recibos.',
    commercialValue:
      'Aproxima o bCost da rotina fiscal completa exigida por operações contábeis maduras.',
    route: '/dashboard/modules/fiscal-obligations',
    apiBase: '/fiscal-obligations',
    mainActions: ['Gerar obrigação', 'Enviar arquivo', 'Anexar recibo', 'Acompanhar status'],
    kpis: ['Pendentes', 'Aceitas', 'Rejeitadas', 'Vencidas'],
  },
  {
    slug: 'employees',
    title: 'Funcionários',
    model: 'Employee',
    area: 'Folha',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Funcionários, CPF, PIS, admissão, regime e salário base.',
    commercialValue: 'Base para folha, Fator R e compliance trabalhista.',
    route: '/dashboard/modules/employees',
    apiBase: '/payroll/employees',
    mainActions: ['Cadastrar funcionário', 'Desligar', 'Editar salário', 'Ver histórico'],
    kpis: ['Ativos', 'Desligados', 'CLT', 'PJ'],
  },
  {
    slug: 'payrolls',
    title: 'Folha Mensal',
    model: 'Payroll',
    area: 'Folha',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Folha, pró-labore, salários e total mensal para Fator R.',
    commercialValue: 'Um dos maiores diferenciais fiscais para Simples Nacional.',
    route: '/dashboard/modules/payrolls',
    apiBase: '/payroll/enterprise/payrolls',
    mainActions: ['Registrar folha', 'Simular pró-labore', 'Fechar competência', 'Ver Fator R'],
    kpis: ['Folha total', 'Pró-labore', 'Fator R', 'Economia possível'],
  },
  {
    slug: 'payroll-entries',
    title: 'Lançamentos de Folha',
    model: 'PayrollEntry',
    area: 'Folha',
    status: 'PLANNED',
    priority: 'MEDIUM',
    description: 'INSS, IRRF, FGTS, benefícios, descontos e salário líquido.',
    commercialValue: 'Permite evoluir para BPO/folha integrada.',
    route: '/dashboard/modules/payroll-entries',
    apiBase: '/payroll/entries',
    mainActions: ['Listar lançamentos', 'Gerar holerite', 'Calcular encargos', 'Exportar folha'],
    kpis: ['INSS', 'IRRF', 'FGTS', 'Salário líquido'],
  },
  {
    slug: 'account-plan',
    title: 'Plano de Contas',
    model: 'AccountPlan',
    area: 'Contábil',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Plano de contas por empresa e tipo contábil.',
    commercialValue: 'Necessário para competir com ERPs contábeis tradicionais.',
    route: '/dashboard/modules/account-plan',
    apiBase: '/accounting/account-plan',
    mainActions: ['Criar conta', 'Editar conta', 'Inativar', 'Importar plano'],
    kpis: ['Ativo', 'Passivo', 'Receita', 'Despesa'],
  },
  {
    slug: 'accounting-entries',
    title: 'Lançamentos Contábeis',
    model: 'AccountingEntry',
    area: 'Contábil',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Débito/crédito, origem automática/manual e competência.',
    commercialValue: 'Núcleo contábil para operar com profundidade de suite contábil profissional.',
    route: '/dashboard/modules/accounting-entries',
    apiBase: '/accounting/entries',
    mainActions: ['Criar lançamento', 'Gerar automático', 'Exportar', 'Bloquear competência'],
    kpis: ['Lançamentos', 'Automáticos', 'Manuais', 'Competências travadas'],
  },
  {
    slug: 'financial-events',
    title: 'Eventos Financeiros',
    model: 'FinancialEvent',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Eventos financeiros: nota emitida, pagamento, imposto, folha e banco.',
    commercialValue: 'Cria linha do tempo financeira auditável.',
    route: '/dashboard/modules/financial-events',
    apiBase: '/finance/events',
    mainActions: ['Ver eventos', 'Filtrar por origem', 'Exportar', 'Auditar'],
    kpis: ['Recebimentos', 'Pagamentos', 'Impostos', 'Eventos manuais'],
  },
  {
    slug: 'financial-snapshots',
    title: 'Snapshots Financeiros',
    model: 'FinancialSnapshot',
    area: 'Financeiro',
    status: 'INTEGRATING',
    priority: 'CRITICAL',
    description: 'DRE mensal, imposto, lucro líquido e hash de integridade.',
    commercialValue: 'Permite fechamento mensal confiável e auditável.',
    route: '/dashboard/modules/financial-snapshots',
    apiBase: '/finance/snapshots',
    mainActions: ['Gerar snapshot', 'Ver DRE', 'Validar hash', 'Comparar meses'],
    kpis: ['Receita', 'Despesas', 'Imposto', 'Lucro líquido'],
  },
  {
    slug: 'cash-flow-projections',
    title: 'Projeção de Caixa',
    model: 'CashFlowProjection',
    area: 'Financeiro',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Previsões de caixa e alertas preditivos.',
    commercialValue: 'Funcionalidade de alto valor percebido para PMEs.',
    route: '/dashboard/modules/cash-flow-projections',
    apiBase: '/finance/cash-flow',
    mainActions: ['Gerar projeção', 'Ver risco', 'Simular cenário', 'Criar alerta'],
    kpis: ['Saldo projetado', 'Risco de caixa', 'Dias até insuficiência'],
  },
  {
    slug: 'audit-logs',
    title: 'Auditoria',
    model: 'AuditLog',
    area: 'Segurança',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Trilha de auditoria por usuário, empresa, entidade e ação.',
    commercialValue: 'Obrigatório para LGPD, enterprise e confiança contábil.',
    route: '/dashboard/modules/audit-logs',
    apiBase: '/audit',
    mainActions: ['Ver logs', 'Filtrar ação', 'Exportar auditoria', 'Investigar evento'],
    kpis: ['Eventos', 'Erros', 'Usuários ativos', 'Tempo médio'],
  },
  {
    slug: 'notifications',
    title: 'Notificações',
    model: 'NotificationLog',
    area: 'SaaS',
    status: 'INTEGRATING',
    priority: 'HIGH',
    description: 'Central de notificações, leitura, reconhecimento e severidade.',
    commercialValue: 'Aumenta engajamento e reduz risco de obrigações esquecidas.',
    route: '/dashboard/modules/notifications',
    apiBase: '/notifications/enterprise',
    mainActions: ['Listar notificações', 'Marcar como lida', 'Reconhecer', 'Filtrar severidade'],
    kpis: ['Pendentes', 'Críticas', 'Lidas', 'Arquivadas'],
  },
  {
    slug: 'compliance-checks',
    title: 'Compliance Fiscal',
    model: 'ComplianceCheck',
    area: 'Compliance',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description: 'Pendências fiscais, severidade, status e resolução.',
    commercialValue: 'Diferencial direto contra contabilidades reativas.',
    route: '/dashboard/modules/compliance-checks',
    apiBase: '/compliance/enterprise/checks',
    mainActions: ['Executar auditoria', 'Resolver pendência', 'Ignorar', 'Gerar relatório'],
    kpis: ['Abertas', 'Resolvidas', 'Críticas', 'Em progresso'],
  },
  {
    slug: 'automation-jobs',
    title: 'Automações',
    model: 'AutomationJob',
    area: 'Automação',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Jobs de automação, progresso, payload, resultado e erro.',
    commercialValue: 'Transforma o bCost em operação automatizada, não só sistema.',
    route: '/dashboard/modules/automation-jobs',
    apiBase: '/automation/jobs',
    mainActions: ['Ver jobs', 'Reprocessar', 'Cancelar', 'Auditar falha'],
    kpis: ['Na fila', 'Executando', 'Concluídos', 'Falhos'],
  },

  {
    slug: 'command-center',
    title: 'Command Center',
    model: 'CommandCenterEnterprise',
    description:
      'Executive Operations Center com score, riscos, módulos, auditoria e atividade operacional consolidada.',
    area: 'Automação',
    status: 'PLANNED',
    priority: 'HIGH',
    commercialValue:
      'Consolida riscos, operações, auditoria e saúde dos módulos enterprise em uma visão executiva única.',
    route: '/dashboard/modules/command-center',
    apiBase: '/operations/command-center',
    mainActions: ['Ver score executivo', 'Analisar riscos', 'Abrir módulos', 'Auditar atividade'],
    kpis: ['Executive Score', 'Healthy', 'Attention', 'Critical', 'Unread'],
  },

  {
    slug: 'audit-intelligence',
    title: 'Audit Intelligence',
    model: 'AuditIntelligenceEnterprise',
    description:
      'Camada enterprise de inteligência de auditoria com quality score, ruído histórico, sinais ativos, recomendações e observabilidade executiva.',
    area: 'Automação',
    status: 'PLANNED',
    priority: 'HIGH',
    commercialValue:
      'Transforma AuditLog e sinais operacionais em inteligência executiva para governança, suporte e observabilidade premium.',
    route: '/dashboard/modules/audit-intelligence',
    apiBase: '/audit/intelligence',
    mainActions: [
      'Analisar qualidade',
      'Ver sinais ativos',
      'Classificar ruído histórico',
      'Priorizar recomendações',
    ],
    kpis: ['Quality Score', 'Active Signals', 'Historical Noise', 'Server Errors', 'Client Errors'],
  },
  {
    slug: 'business-rules',
    title: 'Regras de Negócio',
    model: 'BusinessRule',
    area: 'Automação',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Regras condicionais com ações automáticas por empresa.',
    commercialValue: 'Permite automação fiscal/financeira sem código para o cliente.',
    route: '/dashboard/modules/business-rules',
    apiBase: '/business-rules',
    mainActions: ['Criar regra', 'Ativar/desativar', 'Testar regra', 'Ver disparos'],
    kpis: ['Ativas', 'Inativas', 'Disparos', 'Última execução'],
  },
  {
    slug: 'digital-certificates',
    title: 'Certificados Digitais',
    model: 'DigitalCertificate',
    area: 'Integrações',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Certificados A1, validade, vencimento e status.',
    commercialValue: 'Obrigatório para automação fiscal real com Receita/SEFAZ.',
    route: '/dashboard/modules/digital-certificates',
    apiBase: '/digital-certificates/enterprise',
    mainActions: ['Enviar certificado', 'Ver validade', 'Revogar', 'Alertar vencimento'],
    kpis: ['Ativos', 'Expirados', 'A vencer', 'Revogados'],
  },
  {
    slug: 'webhooks',
    title: 'Webhooks',
    model: 'WebhookConfig',
    area: 'Integrações',
    status: 'PLANNED',
    priority: 'MEDIUM',
    description: 'Webhooks por empresa, eventos, segredo e status ativo.',
    commercialValue: 'Essencial para ecossistema SaaS e integrações B2B.',
    route: '/dashboard/modules/webhooks',
    apiBase: '/webhooks/enterprise',
    mainActions: ['Criar webhook', 'Testar envio', 'Rotacionar segredo', 'Desativar'],
    kpis: ['Ativos', 'Falhas', 'Eventos enviados', 'Último disparo'],
  },
  {
    slug: 'accounting-journal',
    title: 'Diário Contábil',
    model: 'AccountingJournal',
    area: 'Contábil',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description:
      'Livro diário com lançamentos por competência, origem, histórico e trilha de auditoria.',
    commercialValue: 'Fecha a base contábil exigida por escritórios e auditorias profissionais.',
    route: '/dashboard/modules/accounting-journal',
    apiBase: '/accounting/journal',
    mainActions: ['Consultar diário', 'Filtrar competência', 'Exportar livro', 'Validar partidas'],
    kpis: ['Lançamentos', 'Débitos', 'Créditos', 'Diferenças'],
  },
  {
    slug: 'accounting-ledger',
    title: 'Razão Contábil',
    model: 'AccountingLedger',
    area: 'Contábil',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Razão por conta contábil com saldos iniciais, movimentação e saldo final.',
    commercialValue: 'Torna o produto comparável a suites contábeis tradicionais.',
    route: '/dashboard/modules/accounting-ledger',
    apiBase: '/accounting/ledger',
    mainActions: ['Consultar razão', 'Abrir conta', 'Exportar razão', 'Conciliar saldos'],
    kpis: ['Contas movimentadas', 'Saldo devedor', 'Saldo credor', 'Inconsistências'],
  },
  {
    slug: 'trial-balance',
    title: 'Balancete',
    model: 'TrialBalance',
    area: 'Contábil',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Balancete por período com saldo anterior, débitos, créditos e saldo atual.',
    commercialValue: 'Entrega uma peça central da rotina mensal contábil.',
    route: '/dashboard/modules/trial-balance',
    apiBase: '/accounting/trial-balance',
    mainActions: ['Gerar balancete', 'Comparar períodos', 'Exportar PDF', 'Exportar Excel'],
    kpis: ['Ativo', 'Passivo', 'Receitas', 'Despesas'],
  },
  {
    slug: 'balance-sheet',
    title: 'Balanço Patrimonial',
    model: 'BalanceSheet',
    area: 'Contábil',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Balanço patrimonial com ativo, passivo, patrimônio líquido e validações.',
    commercialValue: 'Aumenta maturidade do produto para fechamento anual e consultoria.',
    route: '/dashboard/modules/balance-sheet',
    apiBase: '/accounting/balance-sheet',
    mainActions: [
      'Gerar balanço',
      'Validar equação',
      'Exportar demonstração',
      'Assinar fechamento',
    ],
    kpis: ['Ativo total', 'Passivo total', 'PL', 'Diferença'],
  },
  {
    slug: 'income-statement',
    title: 'DRE',
    model: 'IncomeStatement',
    area: 'Contábil',
    status: 'INTEGRATING',
    priority: 'CRITICAL',
    description:
      'Demonstração do resultado com receita, custos, despesas, tributos e lucro líquido.',
    commercialValue: 'Conecta contabilidade gerencial ao financeiro e ao fiscal.',
    route: '/dashboard/modules/income-statement',
    apiBase: '/accounting/income-statement',
    mainActions: ['Gerar DRE', 'Comparar meses', 'Analisar margem', 'Exportar relatório'],
    kpis: ['Receita', 'Despesas', 'Impostos', 'Lucro líquido'],
  },
  {
    slug: 'ecd',
    title: 'SPED Contábil ECD',
    model: 'EcdFile',
    area: 'Contábil',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Geração, validação e acompanhamento de ECD com recibos e status.',
    commercialValue: 'Obrigação acessória essencial para competir em contabilidade completa.',
    route: '/dashboard/modules/ecd',
    apiBase: '/accounting/ecd',
    mainActions: ['Gerar ECD', 'Validar arquivo', 'Anexar recibo', 'Acompanhar entrega'],
    kpis: ['Pendentes', 'Geradas', 'Transmitidas', 'Rejeitadas'],
  },
  {
    slug: 'ecf',
    title: 'ECF',
    model: 'EcfFile',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Escrituração Contábil Fiscal com apuração, validação, entrega e recibos.',
    commercialValue: 'Cobre uma obrigação crítica para Lucro Presumido e Lucro Real.',
    route: '/dashboard/modules/ecf',
    apiBase: '/fiscal/ecf',
    mainActions: ['Gerar ECF', 'Validar blocos', 'Anexar recibo', 'Acompanhar status'],
    kpis: ['Pendentes', 'Validadas', 'Transmitidas', 'Rejeitadas'],
  },
  {
    slug: 'tax-regime-calculations',
    title: 'Apuração por Regime Tributário',
    model: 'TaxRegimeCalculation',
    area: 'Fiscal',
    status: 'INTEGRATING',
    priority: 'CRITICAL',
    description:
      'Apuração de Simples Nacional, Lucro Presumido e Lucro Real com memória de cálculo.',
    commercialValue: 'Centraliza o motor tributário que diferencia o bCost no mercado.',
    route: '/dashboard/modules/tax-regime-calculations',
    apiBase: '/fiscal/tax-regimes',
    mainActions: ['Apurar Simples', 'Apurar Presumido', 'Apurar Real', 'Comparar regimes'],
    kpis: ['Simples', 'Presumido', 'Real', 'Economia estimada'],
  },
  {
    slug: 'tax-scenarios',
    title: 'Simulador Tributário',
    model: 'TaxScenarioSimulation',
    area: 'Consultoria',
    status: 'ACTIVE',
    priority: 'CRITICAL',
    description:
      'Simulação orientativa PF x PJ, MEI, Simples Nacional e Lucro Presumido com Fator R e impacto informativo CBS/IBS 2026.',
    commercialValue:
      'Cria uma porta consultiva de alto valor para abertura, migração e planejamento tributário assistido, sem substituir parecer CRC.',
    route: '/dashboard/modules/tax-scenarios',
    apiBase: '/tax-scenarios',
    mainActions: [
      'Simular PF x PJ',
      'Comparar regimes',
      'Revisar Fator R',
      'Gerar próximos passos',
    ],
    kpis: ['Melhor regime', 'Carga efetiva', 'Fator R', 'CBS/IBS informativo'],
  },
  {
    slug: 'indirect-taxes',
    title: 'ICMS, IPI, ISS e PIS/COFINS',
    model: 'IndirectTaxCalculation',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Apuração de tributos indiretos, créditos, débitos, retenções, DIFAL e ST.',
    commercialValue: 'Amplia o produto para operações comerciais, serviços e indústria.',
    route: '/dashboard/modules/indirect-taxes',
    apiBase: '/fiscal/indirect-taxes',
    mainActions: ['Apurar ICMS', 'Apurar ISS', 'Calcular PIS/COFINS', 'Validar ST/DIFAL'],
    kpis: ['ICMS', 'ISS', 'PIS/COFINS', 'Retenções'],
  },
  {
    slug: 'sped-fiscal',
    title: 'SPED Fiscal',
    model: 'SpedFiscalFile',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Geração e controle de SPED Fiscal com validações, arquivo e recibo.',
    commercialValue: 'Requisito competitivo para clientes com ICMS/IPI.',
    route: '/dashboard/modules/sped-fiscal',
    apiBase: '/fiscal/sped-fiscal',
    mainActions: ['Gerar SPED', 'Validar arquivo', 'Anexar recibo', 'Auditar blocos'],
    kpis: ['Pendentes', 'Gerados', 'Transmitidos', 'Rejeitados'],
  },
  {
    slug: 'efd-contributions',
    title: 'EFD Contribuições',
    model: 'EfdContributionsFile',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Controle de EFD Contribuições para PIS/COFINS com validação e recibos.',
    commercialValue: 'Completa a esteira fiscal federal para empresas em regimes avançados.',
    route: '/dashboard/modules/efd-contributions',
    apiBase: '/fiscal/efd-contributions',
    mainActions: ['Gerar EFD', 'Validar contribuições', 'Anexar recibo', 'Acompanhar prazo'],
    kpis: ['Pendentes', 'Validadas', 'Transmitidas', 'Rejeitadas'],
  },
  {
    slug: 'federal-obligations',
    title: 'DCTF, DCTFWeb, REINF e PER/DCOMP',
    model: 'FederalObligation',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Agenda e status das obrigações federais, incluindo DEFIS e histórico DIRF.',
    commercialValue: 'Reduz risco operacional e aproxima o bCost da rotina completa do escritório.',
    route: '/dashboard/modules/federal-obligations',
    apiBase: '/fiscal/federal-obligations',
    mainActions: ['Controlar DCTF', 'Controlar REINF', 'Controlar PER/DCOMP', 'Auditar DEFIS/DIRF'],
    kpis: ['Pendentes', 'Transmitidas', 'Vencidas', 'Com recibo'],
  },
  {
    slug: 'fiscal-books',
    title: 'Livros Fiscais',
    model: 'FiscalBook',
    area: 'Fiscal',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Livros de entrada, saída, serviços, apuração e termos fiscais.',
    commercialValue: 'Cobre a escrita fiscal clássica que clientes e contadores esperam.',
    route: '/dashboard/modules/fiscal-books',
    apiBase: '/fiscal/books',
    mainActions: ['Gerar livros', 'Conferir entradas', 'Conferir saídas', 'Exportar livro'],
    kpis: ['Entradas', 'Saídas', 'Serviços', 'Divergências'],
  },
  {
    slug: 'payroll-lifecycle',
    title: 'Ciclo de Folha',
    model: 'PayrollLifecycle',
    area: 'Folha',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Admissão, férias, 13º, rescisão, encargos, pró-labore e eSocial.',
    commercialValue: 'Transforma folha em módulo completo, não apenas cálculo de Fator R.',
    route: '/dashboard/modules/payroll-lifecycle',
    apiBase: '/payroll/lifecycle',
    mainActions: ['Registrar admissão', 'Calcular férias', 'Calcular rescisão', 'Enviar eSocial'],
    kpis: ['Admissões', 'Férias', 'Rescisões', 'Eventos eSocial'],
  },
  {
    slug: 'sst',
    title: 'SST',
    model: 'OccupationalHealthSafety',
    area: 'Folha',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Eventos e controles de Saúde e Segurança do Trabalho integrados ao eSocial.',
    commercialValue: 'Cobre exigências trabalhistas que costumam gerar risco para empresas.',
    route: '/dashboard/modules/sst',
    apiBase: '/payroll/sst',
    mainActions: ['Controlar eventos SST', 'Anexar laudos', 'Acompanhar prazos', 'Auditar envio'],
    kpis: ['Eventos', 'Pendentes', 'Transmitidos', 'Vencidos'],
  },
  {
    slug: 'accounting-office',
    title: 'Gestão de Escritório Contábil',
    model: 'AccountingOfficeOperation',
    area: 'Escritório',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description:
      'Clientes, protocolos, documentos, honorários, CRM interno, atendimento e tarefas.',
    commercialValue:
      'Posiciona o bCost como plataforma de operação do escritório, não só cálculo fiscal.',
    route: '/dashboard/modules/accounting-office',
    apiBase: '/office/operations',
    mainActions: ['Controlar clientes', 'Abrir protocolo', 'Gerir honorários', 'Atender demanda'],
    kpis: ['Clientes', 'Protocolos', 'Tarefas', 'Honorários'],
  },
  {
    slug: 'document-management',
    title: 'Gestão de Documentos',
    model: 'DocumentManagement',
    area: 'Escritório',
    status: 'INTEGRATING',
    priority: 'HIGH',
    description: 'Documentos fiscais, societários, trabalhistas e financeiros por empresa.',
    commercialValue: 'Aumenta retenção e reduz retrabalho em atendimento e auditoria.',
    route: '/dashboard/modules/document-management',
    apiBase: '/documents',
    mainActions: ['Enviar documento', 'Classificar arquivo', 'Vincular protocolo', 'Compartilhar'],
    kpis: ['Documentos', 'Pendentes', 'Assinados', 'Vencidos'],
  },
  {
    slug: 'fixed-assets',
    title: 'Patrimônio e Imobilizado',
    model: 'FixedAsset',
    area: 'Patrimônio',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Ativos, imobilizado, depreciação, baixa e inventário patrimonial.',
    commercialValue: 'Adiciona profundidade contábil e atende empresas com ativos relevantes.',
    route: '/dashboard/modules/fixed-assets',
    apiBase: '/assets/fixed',
    mainActions: ['Cadastrar ativo', 'Calcular depreciação', 'Baixar ativo', 'Gerar inventário'],
    kpis: ['Ativos', 'Depreciação', 'Valor contábil', 'Baixas'],
  },
  {
    slug: 'company-formation',
    title: 'Abertura de Empresa',
    model: 'CompanyFormation',
    area: 'Societário',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'CNPJ, contrato social, inscrição municipal e certificado digital.',
    commercialValue: 'Cria uma porta de entrada comercial para novos clientes contábeis.',
    route: '/dashboard/modules/company-formation',
    apiBase: '/corporate/company-formation',
    mainActions: ['Abrir processo', 'Controlar CNPJ', 'Gerar contrato', 'Solicitar certificado'],
    kpis: ['Processos', 'Em análise', 'Concluídos', 'Pendências'],
  },
  {
    slug: 'banking-products',
    title: 'Banking e Fintech',
    model: 'BankingProduct',
    area: 'Banking',
    status: 'PLANNED',
    priority: 'CRITICAL',
    description: 'Conta PJ com PIX, TED, cartão, cobrança, boletos e conciliação bancária.',
    commercialValue: 'Eleva o produto para competir também na camada financeira/fintech.',
    route: '/dashboard/modules/banking-products',
    apiBase: '/banking/enterprise/products',
    mainActions: ['Ativar PIX', 'Emitir boleto', 'Gerenciar cartão', 'Conciliar banco'],
    kpis: ['PIX', 'Boletos', 'Cartões', 'Conciliações'],
  },
  {
    slug: 'consulting-services',
    title: 'Consultoria e BPO',
    model: 'ConsultingService',
    area: 'Consultoria',
    status: 'PLANNED',
    priority: 'HIGH',
    description: 'Planejamento tributário, BPO financeiro e consultoria humana especializada.',
    commercialValue: 'Diferencia o bCost com serviço assistido e receita premium.',
    route: '/dashboard/modules/consulting-services',
    apiBase: '/consulting/services',
    mainActions: [
      'Solicitar consultoria',
      'Planejar tributos',
      'Operar BPO',
      'Agendar especialista',
    ],
    kpis: ['Demandas', 'Economia estimada', 'BPOs ativos', 'SLA'],
  },
];

export function getSchemaModuleBySlug(slug: string) {
  return bcostSchemaModules.find((module) => module.slug === slug);
}

export function getModulesByArea(area: BcostModuleArea) {
  return bcostSchemaModules.filter((module) => module.area === area);
}

export const bcostModuleAreas: BcostModuleArea[] = [
  'SaaS',
  'Fiscal',
  'Banking',
  'Financeiro',
  'Contábil',
  'Folha',
  'Patrimônio',
  'Societário',
  'Escritório',
  'Compliance',
  'Automação',
  'Integrações',
  'Consultoria',
  'Segurança',
];

export function getModuleStats() {
  return {
    total: bcostSchemaModules.length,
    active: bcostSchemaModules.filter((module) => module.status === 'ACTIVE').length,
    integrating: bcostSchemaModules.filter((module) => module.status === 'INTEGRATING').length,
    planned: bcostSchemaModules.filter((module) => module.status === 'PLANNED').length,
    critical: bcostSchemaModules.filter((module) => module.priority === 'CRITICAL').length,
  };
}
